#!/usr/bin/env bash
set -eo pipefail

# ─────────────────────────────────────────────────────────────
# CrowdDICOM Bootstrap Installer
# When piped via curl, clones the repo and runs scripts/install.sh
# When run locally, generates a .env file for docker-compose
# ─────────────────────────────────────────────────────────────

# Detect if running from a pipe (curl | bash)
if [ -z "${BASH_SOURCE[0]:-}" ] || [ "${BASH_SOURCE[0]:-}" = "bash" ]; then
  # ── Piped mode: bootstrap from GitHub ──
  echo ""
  echo "╔════════════════════════════════════════════════════════════╗"
  echo "║        CrowdDICOM — Bootstrap Installer                   ║"
  echo "╚════════════════════════════════════════════════════════════╝"
  echo ""

  INSTALL_DIR="/opt/crowd-image"
  REPO_URL="https://github.com/chrisgermon/orthanc-dicom-server.git"

  # Must run as root
  if [ "$(id -u)" -ne 0 ]; then
    echo "[ERROR] This script must be run as root. Try: curl -fsSL ... | sudo bash"
    exit 1
  fi

  # Ensure git is available
  if ! command -v git &> /dev/null; then
    echo "[INFO] Installing git..."
    apt-get update -qq && apt-get install -y -qq git > /dev/null 2>&1
  fi

  # Clone or update the repo
  if [ -d "${INSTALL_DIR}/.git" ]; then
    echo "[INFO] Existing installation found. Pulling latest..."
    cd "${INSTALL_DIR}" && git pull origin master
  else
    echo "[INFO] Cloning CrowdDICOM repository..."
    git clone "${REPO_URL}" "${INSTALL_DIR}"
  fi

  # Hand off to the full installer
  echo "[INFO] Launching full installer..."
  exec bash "${INSTALL_DIR}/scripts/install.sh"
fi

# ── Local mode: generate .env for docker-compose ──
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"

echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║        CrowdDICOM — Store-and-Forward Installer           ║"
echo "╠════════════════════════════════════════════════════════════╣"
echo "║  This will configure an Orthanc DICOM server that:       ║"
echo "║   • Receives DICOM images from any modality              ║"
echo "║   • Automatically forwards them to a destination PACS    ║"
echo "║   • Caches locally & cleans up at a disk usage threshold ║"
echo "║   • Logs all operations                                  ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# ── Helper ──────────────────────────────────────────────────
prompt() {
  local var_name="$1"
  local prompt_text="$2"
  local default_value="$3"
  local value

  if [[ -n "$default_value" ]]; then
    read -rp "  ${prompt_text} [${default_value}]: " value < /dev/tty
    value="${value:-$default_value}"
  else
    while [[ -z "${value:-}" ]]; do
      read -rp "  ${prompt_text}: " value < /dev/tty
    done
  fi

  printf -v "$var_name" '%s' "$value"
}

prompt_secret() {
  local var_name="$1"
  local prompt_text="$2"
  local default_value="$3"
  local value

  if [[ -n "$default_value" ]]; then
    read -rsp "  ${prompt_text} [${default_value}]: " value < /dev/tty
    echo ""
    value="${value:-$default_value}"
  else
    while [[ -z "${value:-}" ]]; do
      read -rsp "  ${prompt_text}: " value < /dev/tty
      echo ""
    done
  fi

  printf -v "$var_name" '%s' "$value"
}

# ── Local server settings ──────────────────────────────────
echo "── Local CrowdDICOM Server ──────────────────────────"
echo ""
prompt  LOCAL_AET        "AE Title for this server"              "STORE_FWD"
prompt  LOCAL_DICOM_PORT "DICOM port (external)"                 "4242"
prompt  LOCAL_HTTP_PORT  "HTTP port for web UI (external)"       "8042"
echo ""

# ── Destination PACS settings ──────────────────────────────
echo "── Destination PACS ──────────────────────────────────"
echo ""
prompt  DEST_AET   "Destination PACS AE Title"    ""
prompt  DEST_HOST  "Destination PACS host/IP"     ""
prompt  DEST_PORT  "Destination PACS DICOM port"  "4242"
echo ""

# ── Security ───────────────────────────────────────────────
echo "── Web UI Credentials ────────────────────────────────"
echo ""
prompt        WEB_USER     "Web UI username"   "admin"
prompt_secret WEB_PASSWORD "Web UI password"   "orthanc"
echo ""

# ── Disk management ───────────────────────────────────────
echo "── Disk Management ───────────────────────────────────"
echo ""
prompt  DISK_THRESHOLD  "Max disk usage % before cleanup (0-100)"  "70"
echo ""

# ── Write .env ─────────────────────────────────────────────
cat > "${ENV_FILE}" <<EOF
# ─────────────────────────────────────────────────────────
# Generated by install.sh — $(date '+%Y-%m-%d %H:%M:%S')
# ─────────────────────────────────────────────────────────

# Local Orthanc server
LOCAL_AET=${LOCAL_AET}
LOCAL_DICOM_PORT=${LOCAL_DICOM_PORT}
LOCAL_HTTP_PORT=${LOCAL_HTTP_PORT}

# Destination PACS
DEST_AET=${DEST_AET}
DEST_HOST=${DEST_HOST}
DEST_PORT=${DEST_PORT}

# Web UI credentials
WEB_USER=${WEB_USER}
WEB_PASSWORD=${WEB_PASSWORD}

# Disk management
DISK_THRESHOLD=${DISK_THRESHOLD}
EOF

# ── Create logs directory ─────────────────────────────────
mkdir -p "${SCRIPT_DIR}/logs"

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  ✅  Configuration saved to .env                         ║"
echo "╠════════════════════════════════════════════════════════════╣"
echo "║                                                          ║"
echo "║  Settings Summary:                                       ║"
printf "║  %-56s  ║\n" "Local AE Title:     ${LOCAL_AET}"
printf "║  %-56s  ║\n" "Local DICOM Port:   ${LOCAL_DICOM_PORT}"
printf "║  %-56s  ║\n" "Local HTTP Port:    ${LOCAL_HTTP_PORT}"
printf "║  %-56s  ║\n" "Dest. AE Title:     ${DEST_AET}"
printf "║  %-56s  ║\n" "Dest. Host:         ${DEST_HOST}"
printf "║  %-56s  ║\n" "Dest. Port:         ${DEST_PORT}"
printf "║  %-56s  ║\n" "Web UI User:        ${WEB_USER}"
printf "║  %-56s  ║\n" "Disk Threshold:     ${DISK_THRESHOLD}%"
echo "║                                                          ║"
echo "║  Next steps:                                             ║"
echo "║    docker compose up -d                                  ║"
echo "║                                                          ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
